project_id = "kmwehyixenybegwhqljx"

[functions.wp-password-login]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false

[functions.stripe-historical-backfill]
verify_jwt = false

[functions.redeem-coupon]
verify_jwt = true

[functions.stripe-daily-sync]
verify_jwt = false
