// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/ping.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var ping_default = defineTool({
  name: "ping",
  title: "Ping",
  description: "Health check that echoes a message back. Use to verify the MusicDibs MCP server is reachable.",
  inputSchema: {
    message: z.string().min(1).describe("Text to echo back.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ message }) => ({
    content: [{ type: "text", text: `pong: ${message}` }]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "musicdibs-mcp",
  title: "MusicDibs MCP",
  version: "0.1.0",
  instructions: "Tools exposed by the MusicDibs app (music IP registration on blockchain with AI studio). Use `ping` to verify connectivity. More tools can be added to expose credits balance, works, and AI Studio actions.",
  tools: [ping_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
